require: rubocop-rails

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.1.2
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'public/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'Gemfile'
    - 'Rakefile'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
Style/SymbolArray:
  Exclude:
    - 'app/controllers/api/v1/recipes_controller.rb'