default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: lollys-recipe-api_development


test:
  <<: *default
  database: lollys-recipe-api_test